# Generated by Django 5.1.6 on 2025-06-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_malpracticelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='access_type',
            field=models.CharField(choices=[('protected', 'Protected'), ('unprotected', 'Unprotected')], default='protected', max_length=20),
        ),
    ]
