# Generated by Django 5.1.6 on 2025-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_alter_malpracticelog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpracticelog',
            name='frame',
            field=models.ImageField(blank=True, null=True, upload_to='malpractice_frames/'),
        ),
    ]
