# Generated by Django 5.1.6 on 2025-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_malpracticelog_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_blank_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='allow_jump_around',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_autocomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_right_click',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_spellcheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='only_move_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='penalize_incorrect_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='randomize_order',
            field=models.BooleanField(default=False),
        ),
    ]
