# Generated by Django 5.1.6 on 2025-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_test_access_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpracticelog',
            name='student',
        ),
        migrations.AddField(
            model_name='malpracticelog',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
