# Generated by Django 5.1.6 on 2025-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_remove_malpracticelog_student_malpracticelog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpracticelog',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
