# Generated by Django 5.1.6 on 2025-07-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_test_allow_blank_answers_test_allow_jump_around_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='TestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.test')),
            ],
            options={
                'unique_together': {('test', 'email')},
            },
        ),
    ]
