# Generated by Django 5.1.6 on 2025-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_testattempt_email_testparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allowed_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed emails for protected access', null=True),
        ),
    ]
